[[block]]
text = " | "
color = [255, 255, 0]
align = "right"
min_width = "example"

[[block]]
script = "example.lua"
align = "center"
min_width = "example"
font = "Comic Sans MS"
font_size = 24

[[block]]
text = " | "
color = [0, 255, 255]
align = "left"
min_width = "example"
font = "Arial"
font_size = 14
